---
  - [Ffrench, French]
  - [Murchadha, Murphy]
  - [Quinn, Benjamin, !ruby/regexp /^(Debbie|Deborah)$/]
  - [Astaneh Lopez, Lopez, !ruby/regexp /^Alex$/]
  - [Gardenes Santiago, Gardenes, !ruby/regexp /^Manuel$/]
  - ["O'Siochru", King, !ruby/regexp /^Mairead$/]
